import { readFile, writeFile, mkdir, stat } from "fs/promises";
import { homedir } from "os";
import { join, dirname, resolve } from "path";
import type { ComponentItem } from "./discovery.ts";
import type { ToggleConfig } from "./config.ts";
import { isDisabled } from "./config.ts";

// ============================================================================
// Constants
// ============================================================================

const HOME_DIR = homedir();
const MY_PI_DIR = join(HOME_DIR, ".my-pi");
const HOME_MARKER = "~/.my-pi/";
const ABS_MARKER = MY_PI_DIR + "/";
const MANAGED_START = "<!-- toggle-managed-start -->";
const MANAGED_END = "<!-- toggle-managed-end -->";

// Strips the managed block plus any adjacent blank lines on either side so
// we don't accumulate blank-line drift across edits.
const MANAGED_BLOCK_RE =
  /\n*<!-- toggle-managed-start -->[\s\S]*?<!-- toggle-managed-end -->\n*/;

// Header that precedes the managed block in assembled AGENTS.md files.
const MANAGED_HEADER =
  "## Available Tools\n\n" +
  "_This section is auto-generated by the `toggle` extension. Run `/toggle project` to change which components are enabled. Do not edit between the markers — your changes will be overwritten._";

// ============================================================================
// Snippet Resolution
// ============================================================================

async function fileExists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

/**
 * Locate the SNIPPET.md for a component. Returns null if none exists.
 *
 * - Directory components: `<my-pi>/<relativePath>/SNIPPET.md`
 * - Single-file extensions (.ts): `<my-pi>/<relativePath>.SNIPPET.md`
 *   (detected by the presence of a `.ts` sibling file)
 */
async function resolveSnippetPath(item: ComponentItem): Promise<string | null> {
  const dirCandidate = join(MY_PI_DIR, item.relativePath, "SNIPPET.md");
  if (await fileExists(dirCandidate)) return dirCandidate;

  if (item.type === "extension") {
    const singleFileCandidate = join(MY_PI_DIR, `${item.relativePath}.SNIPPET.md`);
    if (await fileExists(singleFileCandidate)) return singleFileCandidate;
  }

  return null;
}

async function loadSnippet(item: ComponentItem): Promise<string | null> {
  const path = await resolveSnippetPath(item);
  if (!path) return null;
  try {
    return (await readFile(path, "utf-8")).trim();
  } catch {
    return null;
  }
}

// ============================================================================
// Agent Frontmatter Parsing
// ============================================================================

interface AgentMeta {
  name: string;
  description?: string;
  model?: string;
}

function prettyModel(model: string | undefined): string | null {
  if (!model) return null;
  // claude-opus-4-7 → "Opus 4.7", claude-sonnet-4-6 → "Sonnet 4.6"
  const m = model.match(/^claude-(opus|sonnet|haiku)-(\d+)-(\d+)/i);
  if (!m) return model;
  const family = m[1][0].toUpperCase() + m[1].slice(1).toLowerCase();
  return `${family} ${m[2]}.${m[3]}`;
}

async function loadAgentMetaFromPath(agentPath: string, fallbackName: string): Promise<AgentMeta | null> {
  try {
    const content = await readFile(agentPath, "utf-8");
    const match = content.match(/^---\n([\s\S]*?)\n---/);
    if (!match) return { name: fallbackName };
    const fm = match[1];
    const name = fm.match(/^name:\s*(.+)$/m)?.[1]?.trim().replace(/^["']|["']$/g, "") ?? fallbackName;
    const description = fm
      .match(/^description:\s*["']?(.*?)["']?\s*$/m)?.[1]
      ?.trim();
    const model = fm.match(/^model:\s*(.+)$/m)?.[1]?.trim();
    return { name, description, model };
  } catch {
    return null;
  }
}

async function loadAgentMeta(item: ComponentItem): Promise<AgentMeta | null> {
  // Agents live as `<category>/agents/<name>.md`; `relativePath` is the stem
  // (no .md extension), per discovery.ts.
  return loadAgentMetaFromPath(join(MY_PI_DIR, `${item.relativePath}.md`), item.name);
}

function renderAgentLine(meta: AgentMeta): string {
  const model = prettyModel(meta.model);
  const modelTag = model ? ` (${model})` : "";
  const desc = meta.description ? ` — ${meta.description}` : "";
  return `- \`${meta.name}\`${modelTag}${desc}`;
}

// ============================================================================
// Assembly
// ============================================================================

async function buildSection(
  items: ComponentItem[]
): Promise<string | null> {
  const snippets: string[] = [];
  for (const item of items) {
    const snippet = await loadSnippet(item);
    if (snippet) snippets.push(snippet);
  }
  return snippets.length > 0 ? snippets.join("\n\n") : null;
}

async function buildAgentsSection(items: ComponentItem[], extraMetas: AgentMeta[] = []): Promise<string | null> {
  if (items.length === 0 && extraMetas.length === 0) return null;
  const metas = await Promise.all(items.map(loadAgentMeta));
  const lines = [...metas.filter((m): m is AgentMeta => m !== null), ...extraMetas].map(renderAgentLine);
  return lines.length > 0 ? lines.join("\n") : null;
}

function isManagedSettingsEntry(entry: string): boolean {
  const stripped = entry.replace(/^[-!+]\s*/, "").trim();
  return (
    stripped === "~/.my-pi" ||
    stripped === MY_PI_DIR ||
    stripped.startsWith(HOME_MARKER) ||
    stripped.startsWith(ABS_MARKER)
  );
}

function resolveUserAuthoredAgentPath(entry: string, cwd: string): string | null {
  const trimmed = entry.trim();
  if (!trimmed || trimmed.startsWith("-") || trimmed.startsWith("!")) return null;
  if (isManagedSettingsEntry(trimmed)) return null;

  const stripped = trimmed.replace(/^\+\s*/, "").trim();
  if (stripped.startsWith("~/")) return join(HOME_DIR, stripped.slice(2));
  return resolve(cwd, stripped);
}

async function loadUserAuthoredAgentMetas(cwd: string | undefined): Promise<AgentMeta[]> {
  if (!cwd) return [];

  let settings: Record<string, unknown>;
  try {
    settings = JSON.parse(await readFile(join(cwd, ".pi", "settings.json"), "utf-8"));
  } catch {
    return [];
  }

  const entries = Array.isArray(settings.agents) ? settings.agents.filter((e): e is string => typeof e === "string") : [];
  const metas = await Promise.all(
    entries.map(async (entry) => {
      const agentPath = resolveUserAuthoredAgentPath(entry, cwd);
      if (!agentPath) return null;
      const fallbackName = agentPath.split("/").pop()?.replace(/\.md$/, "") || "agent";
      return loadAgentMetaFromPath(agentPath, fallbackName);
    }),
  );

  return metas.filter((m): m is AgentMeta => m !== null);
}

/**
 * Build the full managed block content (including markers).
 * Returns an empty string if there's nothing enabled worth documenting.
 */
export async function buildManagedBlock(
  config: ToggleConfig,
  allItems: ComponentItem[],
  cwd?: string,
): Promise<string> {
  const enabled = allItems.filter((i) => !isDisabled(config, i.relativePath));

  const extensions = enabled.filter((i) => i.type === "extension");
  const agents = enabled.filter((i) => i.type === "agent");
  // Skip superpowers and any skill-category items that don't have their own
  // SNIPPET.md — those either auto-inject via SKILL.md or are intentionally
  // undocumented here.
  const skills = enabled.filter((i) => i.type === "skill");

  const sections: string[] = [];

  const extBlock = await buildSection(extensions);
  if (extBlock) sections.push(`## Extensions\n\n${extBlock}`);

  const userAuthoredAgentMetas = await loadUserAuthoredAgentMetas(cwd);
  const agentBlock = await buildAgentsSection(agents, userAuthoredAgentMetas);
  if (agentBlock) sections.push(`## Agents\n\n${agentBlock}`);

  const skillBlock = await buildSection(skills);
  if (skillBlock) sections.push(`## Skills\n\n${skillBlock}`);

  if (sections.length === 0) return "";

  return `${MANAGED_START}\n\n${MANAGED_HEADER}\n\n${sections.join("\n\n")}\n\n${MANAGED_END}`;
}

// ============================================================================
// Public API
// ============================================================================

/**
 * Assemble {cwd}/AGENTS.md with a managed block listing the snippets for all
 * currently-enabled components. Only runs for project scope — global toggles
 * don't produce an AGENTS.md (tool docs are project-specific by design).
 *
 * If no components are enabled (or none have snippets), the managed block is
 * stripped entirely. If stripping leaves the file empty, it's left empty
 * rather than deleted so pi's file-walk stays deterministic.
 */
export async function assembleProjectAgentsMd(
  config: ToggleConfig,
  allItems: ComponentItem[],
  cwd: string
): Promise<void> {
  const targetPath = join(cwd, "AGENTS.md");

  let existing = "";
  try {
    existing = await readFile(targetPath, "utf-8");
  } catch {
    // File doesn't exist yet — that's fine, we'll create it if we have a block.
  }

  const managedBlock = await buildManagedBlock(config, allItems, cwd);

  // Strip any existing managed block (idempotent).
  const stripped = existing.replace(MANAGED_BLOCK_RE, "\n").replace(/\n+$/, "");

  let newContent: string;
  if (managedBlock) {
    newContent = stripped
      ? `${stripped}\n\n${managedBlock}\n`
      : `${managedBlock}\n`;
  } else {
    newContent = stripped ? `${stripped}\n` : "";
  }

  // If both existing and managed are empty, avoid creating a useless file.
  if (!existing && !managedBlock) return;

  await mkdir(dirname(targetPath), { recursive: true });
  await writeFile(targetPath, newContent, "utf-8");
}
